#!/bin/bash

if [ "$1" = "" ]; then
  echo Must specify database name
  exit 1
fi

source ./ydbenv $1 r128

# copied from db_create
mkdir -p $PWD/$ydb_repl_instname/
$ydb_dist/mumps -r ^GDE @gdemsr
$ydb_dist/mupip create

# copied from repl_setup
$ydb_dist/mupip set -replication=on -region "*"
$ydb_dist/mupip replic -instance_create -noreplace
