#!/bin/bash

if [ "$1" = "" ]; then
  echo Must specify source database name
  exit 1
fi

if [ "$2" = "" ]; then
  echo Must specify target database name
  exit 1
fi

# stop sender at source site
# copied from origination_stop
source ./ydbenv $1 r128
$ydb_dist/mupip replicate -source -shutdown -timeout=2    #Shut down the originating Source Server
$ydb_dist/mupip rundown -region "*"                       #Perform database rundown

# start receiver at target site
# copied from replicating_stop
source ./ydbenv $2 r128
$ydb_dist/mupip replicate -receiver -shutdown -timeout=2   #Shut down the Receiver Server
$ydb_dist/mupip replicate -source -shutdown -timeout=2     #Shut down the passive Source Server

ps -fu `whoami` | grep mupip
